name: meadowlarkCalLUT
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - scipy
  - matplotlib
  - pip
  - pip:
      - "slm[notebooks] @ git+https://github.com/MarKo7s/slm.git@v0.1.0"
      - "cameras[gui,notebooks] @ git+https://github.com/MarKo7s/cameras.git@v0.2.0"
